/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author RYZEN
 */
public class PanelComprarProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelComprarProducto
     */
    public PanelComprarProducto() {
        initComponents();
    }
    
    public void activarBotonComprar(boolean estado){
        btnComprarProducto.setEnabled(estado);
    }
    
    public String getNombre(){
        return txtNombreProducto.getText();
    }
    
    public void setNombre(String nombre){
        txtNombreProducto.setText(nombre);
    }
    
    public int getNumeroVendidos(){
        return Integer.parseInt(txtVendidosProducto.getText());
    }
    
    public void setNumeroVendidos(int numeroVendidos){
        txtVendidosProducto.setText(String.valueOf(numeroVendidos));
    }
    
    public int getInventario(){
        return Integer.parseInt(txtInventarioProducto.getText());
    }
    
    public void setInventario(int numeroInventario){
        txtInventarioProducto.setText(String.valueOf(numeroInventario));
    }
    
    public int getPrecio(){
        return Integer.parseInt(txtPrecioProducto.getText());
    }
    
    public void setPrecio(int precio){
        txtPrecioProducto.setText(String.valueOf(precio));
    }
    
    public void llenarComboProveedores(ArrayList<String> proveedores){
        for (String genero : proveedores)
            {
                comboProvProducto.addItem(genero);
            }
    }
    
    public String getProveedorSeleccionado(){
        return comboProvProducto.getSelectedItem().toString();
    }
    
    public void addBtnComprarProductoListener(ActionListener listenControles){
        btnComprarProducto.addActionListener(listenControles);
    }
    
    public void addBtnVolverListener(ActionListener listenControles){
        btnVolver.addActionListener(listenControles);
    }
    
    public void addBtnCancelarListener(ActionListener listenControles){
        btnCancelar.addActionListener(listenControles);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtVendidosProducto = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        txtInventarioProducto = new javax.swing.JTextField();
        lblNumeroVentas = new javax.swing.JLabel();
        lblNumeroVentas1 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        comboProvProducto = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnComprarProducto = new javax.swing.JButton();
        lblNumeroVentas2 = new javax.swing.JLabel();
        txtCantidadCompra = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListaClientes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblListaClientes.setText("COMPRAR PRODUCTO");
        add(lblListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(176, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCorreo.setText("  Proveedor:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblNombres.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNombres.setText("  Nombre:");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        txtNombreProducto.setEnabled(false);
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, -1));

        txtVendidosProducto.setEnabled(false);
        jPanel1.add(txtVendidosProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

        lblTelefono1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTelefono1.setText("  Vendidos:");
        jPanel1.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtInventarioProducto.setEnabled(false);
        jPanel1.add(txtInventarioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, -1));

        lblNumeroVentas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNumeroVentas.setText("  Invetario:");
        jPanel1.add(lblNumeroVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lblNumeroVentas1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNumeroVentas1.setText("Cantidad:");
        jPanel1.add(lblNumeroVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtPrecioProducto.setEnabled(false);
        jPanel1.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, -1));

        comboProvProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProvProducto.setEnabled(false);
        jPanel1.add(comboProvProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 190, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 86, 158));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, 40));

        btnComprarProducto.setBackground(new java.awt.Color(0, 86, 158));
        btnComprarProducto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnComprarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarProducto.setText("COMPRAR");
        btnComprarProducto.setBorder(null);
        btnComprarProducto.setEnabled(false);
        btnComprarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, 40));

        lblNumeroVentas2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNumeroVentas2.setText("   Precio:");
        jPanel1.add(lblNumeroVentas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));
        jPanel1.add(txtCantidadCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 440, 350));

        btnVolver.setBackground(new java.awt.Color(0, 86, 158));
        btnVolver.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprarProducto;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboProvProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblListaClientes;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumeroVentas;
    private javax.swing.JLabel lblNumeroVentas1;
    private javax.swing.JLabel lblNumeroVentas2;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JTextField txtCantidadCompra;
    private javax.swing.JTextField txtInventarioProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtVendidosProducto;
    // End of variables declaration//GEN-END:variables
}
